(()=>{"use strict";
const KEY="dawg_v3_state";
const CATEGORIES={mental:{name:"Mental",icon:"🧠",desc:"Mindset, reflection and emotional balance",ideas:["Journal for 10 minutes","Write down 3 things I am grateful for","Meditate for 10 minutes","Take 15 minutes away from my phone"]},intellect:{name:"Intellect",icon:"📚",desc:"Learning, studying and building knowledge",ideas:["Study for 2 hours","Read 20 pages","Learn one new concept","Work on a class or personal project"]},physical:{name:"Physical",icon:"💪",desc:"Movement, fitness and taking care of your body",ideas:["Work out for 45 minutes","Go for a 30 minute walk","Stretch for 15 minutes","Get outside and move for 20 minutes"]},discipline:{name:"Discipline",icon:"⚡",desc:"Doing what you said you would do",ideas:["Wake up at my planned time","Finish my hardest task first","Keep my room/workspace organized","No unnecessary scrolling during work"]},social:{name:"Social",icon:"🤝",desc:"Relationships, communication and community",ideas:["Call or text a friend","Talk to someone new","Spend intentional time with family","Reach out to someone I have not talked to recently"]},ambition:{name:"Ambition",icon:"🚀",desc:"Goals, career, projects and future growth",ideas:["Work 30 minutes on my biggest goal","Build something for my portfolio","Apply to an opportunity","Plan tomorrow's top 3 priorities"]}};
const ranks=["Initiate","Rising","Focused","Driven","Elite","Apex","Legend"];
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function fresh(){return{goals:[],xp:0,streak:0,bestStreak:0,lastCompletedDay:null,history:{},journal:{},setupComplete:false}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&Array.isArray(x.goals)?{...fresh(),...x}:fresh()}catch(e){return fresh()}}
let state=load(),timer=1500,timerId=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function offset(n){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function level(){return Math.floor(state.xp/100)+1}
function rankIndex(){return Math.min(ranks.length-1,Math.floor((level()-1)/5))}
function rank(){return ranks[rankIndex()]}
function categoryGoals(c){return state.goals.filter(g=>g.category===c)}
function completedCount(){return state.goals.filter(g=>g.done).length}
function score(){return state.goals.length?Math.round(completedCount()/state.goals.length*100):0}
function render(){const done=completedCount(),total=state.goals.length,s=score(),l=level(),into=state.xp%100;$("level").textContent=l;$("rank").textContent=rank();$("xpText").textContent=`${into} / 100 XP`;$("xpBar").style.width=into+"%";$("streak").textContent=state.streak+" 🔥";$("today").textContent=`${done}/${total}`;$("score").textContent=s+"%";$("scoreMini").textContent=s+"%";$("scoreBar").style.width=s+"%";$("scoreMessage").textContent=s===100?"Perfect day.":s>=60?"Finish strong.":s?"Momentum is building.":"Start with one.";renderGoals();renderManager();renderProgress();renderHistory();loadJournal()}
function renderGoals(){const el=$("habitList");el.innerHTML="";if(!state.goals.length){el.innerHTML='<div class="empty">Your goals will appear here after setup.</div>';return}Object.keys(CATEGORIES).forEach(c=>{const gs=categoryGoals(c);if(!gs.length)return;const head=document.createElement("div");head.className="category-heading";head.innerHTML=`<span>${CATEGORIES[c].icon} ${CATEGORIES[c].name}</span><small>${gs.filter(g=>g.done).length}/${gs.length}</small>`;el.append(head);gs.forEach(g=>{const r=document.createElement("div");r.className="habit";const b=document.createElement("button");b.type="button";b.className="check"+(g.done?" done":"");b.textContent=g.done?"✓":"";b.addEventListener("click",()=>toggle(g.id));const i=document.createElement("div");i.className="habit-info";i.innerHTML='<div class="habit-name"></div><div class="habit-meta"></div>';i.querySelector(".habit-name").textContent=g.name;i.querySelector(".habit-meta").textContent=g.done?"Completed today":CATEGORIES[g.category].name;const x=document.createElement("span");x.className="xp";x.textContent="+"+g.xp+" XP";r.append(b,i,x);el.append(r)})})}
function renderManager(){const el=$("categoryManager");el.innerHTML="";Object.keys(CATEGORIES).forEach(c=>{const gs=categoryGoals(c),box=document.createElement("div");box.className="manager-category";box.innerHTML=`<div class="category-title"><span>${CATEGORIES[c].icon} <strong>${CATEGORIES[c].name}</strong></span><span class="count ${gs.length?"valid":""}">${gs.length} goal${gs.length===1?"":"s"}</span></div><small>${CATEGORIES[c].desc}</small>`;gs.forEach(g=>{const row=document.createElement("div");row.className="manage-row";row.innerHTML='<div class="manage-goal"></div><button class="delete" type="button">Delete</button>';row.querySelector(".manage-goal").textContent=g.name;row.querySelector(".delete").addEventListener("click",()=>removeGoal(g.id));box.append(row)});el.append(box)})}
function renderSetup(){const el=$("setupCategories");el.innerHTML="";Object.keys(CATEGORIES).forEach(c=>{const gs=categoryGoals(c),box=document.createElement("div");box.className="setup-category";box.innerHTML=`<div class="category-title"><span>${CATEGORIES[c].icon} <strong>${CATEGORIES[c].name}</strong></span><span class="count ${gs.length?"valid":""}">${gs.length?"✓ Added":"Required"}</span></div><small>${CATEGORIES[c].desc}</small><button class="setup-add" type="button">${gs.length?"Add another":"＋ Add a goal"}</button><div class="setup-goals"></div>`;const list=box.querySelector(".setup-goals");gs.forEach(g=>{const p=document.createElement("div");p.className="setup-goal";p.textContent=g.name;list.append(p)});box.querySelector(".setup-add").addEventListener("click",()=>openGoal(c));el.append(box)});const count=Object.keys(CATEGORIES).filter(c=>categoryGoals(c).length).length;$("setupCount").textContent=`${count} / 6`;$("finishSetup").disabled=count<6}
function statScore(c){const gs=categoryGoals(c);if(!gs.length)return 0;const completed=gs.filter(g=>g.done).length;const historical=Object.values(state.history).reduce((n,d)=>n+(d.categoryXP?.[c]||0),0);const current=gs.filter(g=>g.done).reduce((n,g)=>n+g.xp,0);return Math.min(100,Math.round((completed/gs.length)*70+Math.min(30,(historical+current)/100*30)))}
function renderProgress(){const l=level(),ri=rankIndex(),base=ri*5,within=Math.min(5,Math.max(0,l-base)),pct=ri===ranks.length-1?100:within/5*100;$("progressRank").textContent=rank();$("progressLevel").textContent="LVL "+l;$("rankNow").textContent=rank();$("rankNext").textContent=ri<ranks.length-1?ranks[ri+1]:"MAX";$("rankBar").style.width=pct+"%";$("rankTrack").innerHTML=ranks.map((r,i)=>`<div class="rank-node ${i===ri?"current":i<ri?"passed":""}"><span>${i+1}</span><small>${r}</small></div>`).join("");drawRadar(Object.keys(CATEGORIES).map(statScore));$("categoryStats").innerHTML=Object.keys(CATEGORIES).map(c=>`<div class="cat-stat"><span>${CATEGORIES[c].icon}</span><div><strong>${CATEGORIES[c].name}</strong><div class="mini-progress"><i style="width:${statScore(c)}%"></i></div></div><b>${statScore(c)}</b></div>`).join("");const history=Object.values(state.history),days=history.filter(x=>x.completed).length,avg=history.length?Math.round(history.reduce((a,x)=>a+x.score,0)/history.length):0;$("totalXP").textContent=state.xp;$("bestStreak").textContent=state.bestStreak+" 🔥";$("daysDone").textContent=days;$("avgScore").textContent=avg+"%";const a=[["🔥","First Step","Complete your first day",days>=1],["⚡","7 Day Warrior","Reach a 7 day streak",state.bestStreak>=7],["🏆","Level 5","Reach level 5",l>=5],["💪","Consistent","Complete 10 days",days>=10]];$("achievements").innerHTML=a.map(x=>`<div class="achievement ${x[3]?"":"locked"}"><div class="icon">${x[0]}</div><div><strong>${x[1]}</strong><small>${x[2]}</small></div></div>`).join("")}
function drawRadar(values){const canvas=$("radar"),ctx=canvas.getContext("2d"),dpr=window.devicePixelRatio||1,size=320;canvas.width=size*dpr;canvas.height=size*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,size,size);const cx=160,cy=160,r=105,n=6;ctx.lineWidth=1;ctx.strokeStyle="rgba(255,255,255,.12)";for(let ring=1;ring<=4;ring++){ctx.beginPath();for(let i=0;i<n;i++){const a=-Math.PI/2+i*2*Math.PI/n,x=cx+Math.cos(a)*r*ring/4,y=cy+Math.sin(a)*r*ring/4;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke()}for(let i=0;i<n;i++){const a=-Math.PI/2+i*2*Math.PI/n;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);ctx.stroke()}ctx.beginPath();values.forEach((v,i)=>{const a=-Math.PI/2+i*2*Math.PI/n,x=cx+Math.cos(a)*r*v/100,y=cy+Math.sin(a)*r*v/100;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle="rgba(255,255,255,.13)";ctx.fill();ctx.strokeStyle="rgba(255,255,255,.75)";ctx.stroke();ctx.fillStyle="#9999a3";ctx.font="700 10px system-ui";ctx.textAlign="center";Object.keys(CATEGORIES).forEach((c,i)=>{const a=-Math.PI/2+i*2*Math.PI/n;ctx.fillText(CATEGORIES[c].name,cx+Math.cos(a)*(r+25),cy+Math.sin(a)*(r+25)+3)})}
function renderHistory(){const el=$("history");el.innerHTML="";for(let i=-6;i<=0;i++){const k=offset(i),item=state.history[k],d=new Date(k+"T12:00:00"),r=document.createElement("div");r.className="day";r.innerHTML=`<div class="day-name">${d.toLocaleDateString(undefined,{weekday:"short"})}</div>`;const b=document.createElement("div");b.className="day-box";if(item?.score===100){b.classList.add("done");b.textContent="✓"}else if(item?.score>0){b.classList.add("partial");b.textContent=item.score+"%"}else b.textContent="—";r.append(b);el.append(r)}}
function toggle(id){const g=state.goals.find(x=>x.id===id);if(!g)return;if(g.done){g.done=false;state.xp=Math.max(0,state.xp-g.xp);toast("Goal unchecked.")}else{g.done=true;state.xp+=g.xp;toast("+"+g.xp+" XP · "+CATEGORIES[g.category].name)}save();render()}
function removeGoal(id){const g=state.goals.find(x=>x.id===id);if(!g)return;if(g.done)state.xp=Math.max(0,state.xp-g.xp);state.goals=state.goals.filter(x=>x.id!==id);save();render();toast("Goal removed.")}
function openGoal(category){$("goalModal").classList.remove("hidden");$("goalCategory").innerHTML=Object.keys(CATEGORIES).map(c=>`<option value="${c}">${CATEGORIES[c].icon} ${CATEGORIES[c].name}</option>`).join("");if(category)$("goalCategory").value=category;$("goalInput").value="";$("ideaList").classList.add("hidden");$("goalInput").focus()}
function closeGoal(){$("goalModal").classList.add("hidden")}
function addGoal(){const name=$("goalInput").value.trim(),category=$("goalCategory").value;if(!name){toast("Enter a goal first.");return}state.goals.push({id:uid(),name,category,xp:10,done:false});save();closeGoal();render();renderSetup();toast("Goal added to "+CATEGORIES[category].name+".")}
function showIdeas(){const c=$("goalCategory").value,el=$("ideaList");el.innerHTML=CATEGORIES[c].ideas.map((x,i)=>`<button type="button" data-idea="${i}">${x}<span>＋</span></button>`).join("");el.classList.remove("hidden");el.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{$("goalInput").value=CATEGORIES[c].ideas[Number(b.dataset.idea)];el.classList.add("hidden")}))}
function complete(){const total=state.goals.length,done=completedCount();if(!total){toast("Add your six areas first.");return}if(done<total){toast(`${total-done} goal${total-done===1?"":"s"} left. Finish them all first.`);return}const k=today();if(state.history[k]?.completed){toast("Today is already completed.");return}const categoryXP={};state.goals.forEach(g=>categoryXP[g.category]=(categoryXP[g.category]||0)+g.xp);state.streak=state.lastCompletedDay===offset(-1)?state.streak+1:1;state.bestStreak=Math.max(state.bestStreak,state.streak);state.lastCompletedDay=k;state.history[k]={completed:true,score:100,categoryXP};save();render();toast("Day completed. Streak +1 🔥")}
function toast(s){const e=$("toast");e.textContent=s;clearTimeout(toast.t);toast.t=setTimeout(()=>e.textContent="",1900)}
function nav(page){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===page));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.page===page));if(page==="progress")renderProgress()}
document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>nav(b.dataset.page)));
$("addGoalBtn").addEventListener("click",()=>openGoal());$("addGoalBtn2").addEventListener("click",()=>openGoal());$("closeGoal").addEventListener("click",closeGoal);$("saveGoal").addEventListener("click",addGoal);$("ideasBtn").addEventListener("click",showIdeas);$("goalCategory").addEventListener("change",()=>{$("ideaList").classList.add("hidden")});$("finishSetup").addEventListener("click",()=>{const ok=Object.keys(CATEGORIES).every(c=>categoryGoals(c).length);if(!ok){toast("Every area needs at least one goal.");return}state.setupComplete=true;save();$("setupModal").classList.add("hidden");render();toast("Your DAWG system is ready.")});$("completeDay").addEventListener("click",complete);
$("resetBtn").addEventListener("click",()=>{if(confirm("Reset all DAWG progress and goals?")){state=fresh();save();render();renderSetup();$("setupModal").classList.remove("hidden");toast("System reset.")}});
$("saveJournal").addEventListener("click",()=>{state.journal[today()]=$("journalText").value;save();$("journalSaved").textContent="Saved.";setTimeout(()=>$("journalSaved").textContent="",1600)});function loadJournal(){$("journalText").value=state.journal[today()]||""}
$("startTimer").addEventListener("click",()=>{if(timerId){clearInterval(timerId);timerId=null;$("startTimer").textContent="Resume";return}$("startTimer").textContent="Pause";timerId=setInterval(()=>{timer--;updateTimer();if(timer<=0){clearInterval(timerId);timerId=null;toast("Focus session complete.");$("startTimer").textContent="Start"}},1000)});$("resetTimer").addEventListener("click",()=>{clearInterval(timerId);timerId=null;timer=1500;updateTimer();$("startTimer").textContent="Start"});
function updateTimer(){const m=Math.floor(timer/60),s=timer%60;$("timer").textContent=String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}
const hour=new Date().getHours();$("greeting").textContent=hour<12?"GOOD MORNING":hour<18?"GOOD AFTERNOON":"GOOD EVENING";updateTimer();if(!state.setupComplete){renderSetup();$("setupModal").classList.remove("hidden")}render();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});window.addEventListener("resize",()=>{if($("progress").classList.contains("active"))renderProgress()});
})();